### ISSUE TITLE
Exact duplicates of sentences in dev & test

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_Italian-VIT#4]
Sentence VIT-4525 in dev and VIT-4769 in test are exact duplicates, with the rather dubious difference that word #9 has a different head in the two examples.

**Comment by dan-zeman** [comment]
5 `nmod` (VIT-4769) seems correct!

**Comment by AngledLuffa** [comment]
Great, thanks!  Any suggestions on what to do about there being two copies of the same sentence, or is that okay?

**Comment by dan-zeman** [comment]
> Great, thanks! Any suggestions on what to do about there being two copies of the same sentence, or is that okay?

If it were just one sentence out of 10,000, I wouldn't see it as a problem. Here the surrounding sentences are duplicate, too; but when going futher down, there are small differences in the texts. It could be two versions of one regulatory document, starting at VIT-4524 in dev and VIT-4768 in test. For example, 4531 vs. 4775 differ in date (_10 settembre_ vs. _primo settembre_); 4532 vs. 4776 differ in tense (_è documentata_ vs. _va documentata_).

I find it a bit unfortunate that one version of the document is in the dev data and the other version is in the test data, but the main question is about the actual extent of the problem. One changed word will prevent the sentence from being identified as duplicate, although it is still almost as if the parser saw the test data in advance. The tests ([overlap.py](https://github.com/UniversalDependencies/tools/blob/master/overlap.py)) before release 2.9 identified just one true duplicate sentence between dev and test, plus 4 shorter sentences between dev and train:

    " no .
    38 Spoleto festival .
    Bianca nera .
    La tragedia in riva a il mare .

This does not look like something to worry about, but if there are dozens of pseudo-duplicates with only tiny differences, it could be a problem. Maybe @msimi can comment on it?

**Comment by msimi** [comment]
Dear all,

As you may be aware, we received the data from the original developers of the VIT treebank (Del Monte & c. In Venice) and converted the treebank to UD.
Fabio Tamburini (cc in this mail) from the University of Bologna helped in the conversion. 

I may inquire about the source of the data and the extent of the problem. 
In some cases there are similar phrases with small variations just to test different parsing outcomes. In this case it was intentional.
In other cases "It appears to be two versions of one regulatory document” as Zeman noticed.

What I am sure of is that replications are natural, i.e. nobody introduced small variations to prevent the sentence from being identified as duplicate.
The splitting in train, dev, test was performed randomly. It can be done differently, if needed, keeping together documents of the same type.

— Best,
— Maria

**Comment by amir-zeldes** [comment]
I don't know anything about this particular case, but I think in general, the parser having seen a sentence in train is not a 100% exclusion criterion for test. If the data is truly randomly distributed, and this corpus models for example the 'regulatory document' domain, then it is reasonable for there to be a chance of sentences repeating (since it's a formulaic, repetitive domain). In that case parser performance evaluated on test is realistic: it tells us that the parser will do rather well, since even in totally new unseen documents from this domain, some sentences will recur (and in fact test allows us to estimate this proportion of exact or near duplicates). So unless it's a systematic duplication of documents due to corpus design/splitting errors, I would say it's a natural property of this data and should be left alone.

**Comment by AngledLuffa** [comment]
Thanks for the feedback, everyone.  We updated the dependencies to be the same and left the trees alone in #5.
